CREATE TABLE public.intraday_dc_data (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_time timestamp NOT NULL,
	plant_name varchar NOT NULL,
	dc_data float8 NOT NULL,
	plant_id int4 NOT NULL,
	CONSTRAINT intraday_dc_table_pk PRIMARY KEY (id),
	CONSTRAINT intraday_dc_table_un UNIQUE (date_time,plant_id)
);
